### ISSUE TITLE
Task list for version 0.1.0

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#22]
Major features that will be included in this release:
- ~Develop `Process` class @joyxyz1994~
  - This seems will take longer time, move to version 0.2.0 #25
- [x] Enable Morris and Sobol sensitivity analysis in `QSDsan`, ~either with updates in `BioSTEAM` or~ as a standalone module in `QSDsan` @yalinli2 
  - Sobol done in commit 90c71caed192f2134a9b528f02fd8372847e2c09
  - Pearson, Spearman, and Morris done in commit 5f5109f77ae56f045afbb1d203aac8a6165bbc31
  - Morris plotting function added in commit 59dfef5f4842321de040ca761b9ff19020fa281e
- [x] Add uncertainty models to all three scenarios in the `bwaise` system, ~potentially~ demonstrate how Morris and Sobol can be performed @yalinli2 
  - All uncertainty models/parameters added in commit 40512de705026d6e58013f5921defd2fd260c459
  - A demonstrative script for using Morris and Sobol have been added in commit 741342cece5d2f6c1ecbc96e891c2554e0efceb9
  - ~I noticed this [paper](https://www.frontiersin.org/articles/10.3389/fninf.2018.00049/full) on `Uncertainpy`, which was built on `Chaospy` and `SALib`, might consider using this package in the future, but for now, still plan to use `SALib`~
    - `Uncertainpy` seems to be geared toward neuroscience, `Chaospy` and `SALib` are sufficient
- [x] Replace the `get_normalized_impacts` method in `LCA` with something like `get_allocated_impacts`, and allow users to allocate the impacts based on mass, value, energy, or a ratio/function provided by the user @yalinli2 
  -   Done in commit a4453b01b141d62ce669762ff9c691030ba96362
