### ISSUE TITLE
Task list for version 0.2.0

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#25]
Major features that will be included in this release:
- [x] Develop `Process` class @joyxyz1994 bfa51a60e8ce0590e27e01068751b9c6eb29b2b9
- [x] Add an `Equipment` class to account for the different equipment in a `SanUnit` d80e7912b7f2ca4c0f46a8fc6d3b921bf9334b26   
- [x] Add additional sensitivity analyses and visualization functions
    - (e)FAST and RBD-FAST 0738db5aeab53e59a054aff021612d2e77ad930d
    - Test Morris convergence 2e97f84436b37567b2cb91ee24bc618ecaa5b737
- [x] (Nice) plotting functions to visualize statistical analyses, with [examples:](https://qsdsan-beta.readthedocs.io/en/latest/stats.html)
    - Uncertainty analysis 694fff0a11d3b9f2576408e9d0842909fabf67b8 
    - Correlation analyses 694fff0a11d3b9f2576408e9d0842909fabf67b8
    - (e)FAST and RBD-FAST 0738db5aeab53e59a054aff021612d2e77ad930d
    - Morris convergence 2e97f84436b37567b2cb91ee24bc618ecaa5b737
    - Sobol 6e9b20200202296f1428085e2a18153a699217db

**Comment by yalinli2** [comment]
v0.2.0 released, issue closed! 319dd9d083b1b4204db7782e046cc8da7eacef2e
