### ISSUE TITLE
Task list for v0.3.0

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#33]
Updates to be included in v0.3.0 release
- [x] Separate developed systems into a standalone repository/package [`EXPOsan`](https://github.com/QSD-Group/exposan) 68f21e2b19a4398951b5d91de71aa0620c87042d
- [x] Make it possible to use both `Stream` and `WasteStream` 4acc8d785489caadac03add3023d17bbc3e7bd29
  - Also added a new `SanStream` class (`tmo.Stream` plus with `impact_item`), now `SanUnit` can be initialized by any of these three classes, and they can be mixed.
- [x] Enable LCA data importing
  - This will be done through via [brightway2](https://github.com/brightway-lca/brightway2). Kudos to the brightway2 development group for the awesome capacities, the package (with the detailed documentations and tutorials),  it's seriously underrated.
  - DONE!!! 🎉  73e6d8144a8b28e592e797bfa7e8a4e0951db2f5 with the new package [``BW2QSD``](https://github.com/QSD-Group/BW2QSD), though will definitely need more testing to make sure it works, and add support for databases other than ecoinvent.
- [x] Add examples in documentation
  -  With df36e5022810398d8740bf56062a7b1a8ad4172e there are direct examples/links to examples in major classes, will continue to work on this along the way.

**Comment by yalinli2** [comment]
OK with this commit 3c19ae v0.3.0 is released! Closing this issue!
