### ISSUE TITLE
Merging `gates` into `main`

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan#70]
Thanks to everyone (@haclohman in particular for leading and going through the codes for each system), we are close to merging the systems in the `gates` branch` into `main`, just want to document some changes I'd like to make before pulling those in:

- [x] Consolidate the modules, see #56 
- [x] Make sure references are good, see #58 
- [x] Consistent `SanUnit`
    - Add in required Component/ImpactItem in unit docs, see #51
    - Remove legacy comments, see #57
    - Update `__init__`, see #59
- [x] Make sure the units are included in tests, either through doctest or through testing the corresponding system, see #52

**Comment by yalinli2** [comment]
Just a note that this is ongoing in the private repo because of the NDA, but all units that can be public will go public when it's done

**Comment by yalinli2** [comment]
The `gates` branch has been merged in: #75 
Note that the data sheets/references for some module still needs to be checked/updated, but those are minor and will be made to the `main` branch
